services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data    # Чтобы видеть изменения в dev-режиме (убери, если не нужен hot reload)
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://todo_user:todo_pass@db:5432/todo_db
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  pgdata:

#Последняя сборочная проверка с авто-пуллом изменений 
