services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
      - ./logs/backend:/app/logs  # собираем логи сюда, если пишешь в файл
    expose:
      - 8000
    environment:
      DATABASE_URL: postgresql+psycopg2://todo_user:todo_pass@db:5432/todo_db
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx  # добавим маппинг для логов nginx
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # для старта, не для продакшна
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    ports:
      - 5044:5044  # для filebeat
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.0
    user: root  # нужен root для доступа к логам контейнеров
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/nginx:/var/log/nginx:ro
      - ./logs/backend:/var/log/backend:ro
    depends_on:
      - logstash
    entrypoint: ["filebeat", "-e"]

volumes:
  pgdata:
  esdata:
