version: "3.9"

services:
  db:
    image: postgres:16
    container_name: todo-db
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: todo-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://todo_user:todo_pass@db:5432/todo_db
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata:
