- name: Install dependencies for Full-project
  hosts: full_project
  become: true
  vars:
    project_root: /home/user1/app
  tasks:
    - name: Install system packages
      apt:
        update_cache: yes
        name:
          - python3
          - python3-pip
          - python3-venv
          - build-essential
          - libpq-dev
          - nodejs
          - npm
        state: present

    - name: Install backend Python dependencies
      pip:
        requirements: "{{ project_root }}/backend/requirements.txt"
        virtualenv: "{{ project_root }}/venv"
        virtualenv_python: python3

    - name: Install root Node dependencies
      npm:
        path: "{{ project_root }}"

    - name: Install frontend Node dependencies
      npm:
        path: "{{ project_root }}/frontend"