- name: Install dependencies for Full-project
  hosts: full_project
  become: true
  vars:
    project_root: /home/user1/app
  tasks:
    - name: Install system packages
      apt:
        update_cache: yes
        name:
          - docker
        state: present



